from flask_wtf import Form
from wtforms import StringField, IntegerField
from wtforms.validators import DataRequired

class ScheduleCreator(Form):
    name = StringField('name', validators=[DataRequired()])
    course1 = StringField('course1', validators=[DataRequired()], default='NC')
    start_time1hour = IntegerField('start_time1hour', default=0)
    start_time1min = IntegerField('start_time1min', default=0)
    end_time1hour = IntegerField('end_time1hour', default=0)
    end_time1min = IntegerField('end_time1min', default=0)
    course2 = StringField('course2', validators=[DataRequired()], default='NC')
    start_time2hour = IntegerField('start_time2hour', default=0)
    start_time2min = IntegerField('start_time2min', default=0)
    end_time2hour = IntegerField('end_time2hour', default=0)
    end_time2min = IntegerField('end_time2min', default=0)
    course3 = StringField('course3', validators=[DataRequired()], default='NC')
    start_time3hour = IntegerField('start_time3hour', default=0)
    start_time3min = IntegerField('start_time3min', default=0)
    end_time3hour = IntegerField('end_time3hour', default=0)
    end_time3min = IntegerField('end_time3min', default=0)
    course4 = StringField('course4', validators=[DataRequired()], default='NC')
    start_time4hour = IntegerField('start_time4hour', default=0)
    start_time4min = IntegerField('start_time4min', default=0)
    end_time4hour = IntegerField('end_time4hour', default=0)
    end_time4min = IntegerField('end_time4min', default=0)
    course5 = StringField('course5', validators=[DataRequired()], default='NC')
    start_time5hour = IntegerField('start_time5hour', default=0)
    start_time5min = IntegerField('start_time5min', default=0)
    end_time5hour = IntegerField('end_time5hour', default=0)
    end_time5min = IntegerField('end_time5min', default=0)
